### ISSUE TITLE
Error: psql: FATAL:  could not access file "$libdir/plugins/pgextwlist": No such file or directory

### ISSUE THREAD

**Issue by alhafoudh** [dimitri/pgextwlist#1]
Hi,
I get error when running "psql" command:

psql: FATAL:  could not access file "$libdir/plugins/pgextwlist": No such file or directory

**Comment by ChristophBerg** [comment]
The README.md file mentions pkglibdir/plugins, so closing this now.

**Comment by strk** [comment]
Wouldn't it make more sense for `make install` to directly install under plugins/ instead ?

**Comment by df7cb** [comment]
> Wouldn't it make more sense for `make install` to directly install under plugins/ instead ?

Maybe, but so far I was reluctant to change existing behavior.
