### ISSUE TITLE
Error message regression

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [dimitri/pgextwlist#13]
Used to get a nice, helpful error from pgextwlist, but now it complains about missing control files regardless of the extension we try to create:

```
=> create extension "does-not-exist";
ERROR:  could not open extension control file "/usr/share/postgresql/9.3/extension/does-not-exist.control": No such file or directory
```

**Comment by df7cb** [comment]
This is the standard message for non-existing extensions, there's little can (and should) change here.
