### ISSUE TITLE
PostgreSQL lib location not correct on some platforms?

### ISSUE THREAD

**Issue by GeorgeDewar** [dimitri/pgextwlist#18]
I notice that your Readme file says to put pgextwlist.so in `pg_config --libdir`/plugins. On two machines I've used - Ubuntu 12.04.3 and Ubuntu 13.10, this location consistently is reported as /usr/lib (i.e. /usr/lib/plugins) - whether I run the command as my normal user or as postgres.

However, /usr/lib/plugins does not appear to be a suitable location for the file. What I've found works is /usr/lib/postgresql/9.1/lib/plugins.

Is it possible to adjust either the make script so that it puts it in that location anyway, or the Readme file so that the instructions work for users on Ubuntu?

My apologies if I have in fact misunderstood the situation and the instructions do work.

**Comment by ChristophBerg** [comment]
README.md documents the use of --pkglibdir since a while, closing this.
