### ISSUE TITLE
Does not build with Postgres 10

### ISSUE THREAD

**Issue by bradnicholson** [dimitri/pgextwlist#26]
I tried to build with PG 10 Beta 1, it fails

```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -I. -I./ -I/usr/local/postgres/10beta1/include/server -I/usr/local/postgres/10beta1/include/internal   -c -o utils.o utils.c
In file included from utils.c:25:
./utils.h:33:11: error: unknown type name 'List'
                                                                  List *options,
                                                                  ^
utils.c:404:15: error: too few arguments to function call, expected 5, have 4
                                                                                   0);
                                                                                    ^
/usr/local/postgres/10beta1/include/server/tcop/tcopprot.h:51:1: note: 'pg_analyze_and_rewrite' declared here
extern List *pg_analyze_and_rewrite(RawStmt *parsetree,
^
utils.c:428:24: error: too few arguments to function call, expected 8, have 7
                                                                                dest, NULL, 0);
                                                                                             ^
/usr/local/postgres/10beta1/include/server/executor/execdesc.h:59:1: note: 'CreateQueryDesc' declared here
extern QueryDesc *CreateQueryDesc(PlannedStmt *plannedstmt,
^
utils.c:431:47: error: too few arguments to function call, expected 4, have 3
                                ExecutorRun(qdesc, ForwardScanDirection, 0);
                                ~~~~~~~~~~~                               ^
/usr/local/postgres/10beta1/include/server/executor/executor.h:170:1: note: 'ExecutorRun' declared here
extern void ExecutorRun(QueryDesc *queryDesc,
^
utils.c:445:15: error: too few arguments to function call, expected 7, have 6
                                                           NULL);
                                                               ^
/usr/local/postgres/10beta1/include/server/tcop/utility.h:34:1: note: 'ProcessUtility' declared here
extern void ProcessUtility(PlannedStmt *pstmt, const char *queryString,
^
5 errors generated.
make: *** [utils.o] Error 1
```

**Comment by dimitri** [comment]
In each PostgreSQL versions, some function prototypes and internal API change, and we need to adjust the code for that. It is usually pretty easy to do so, here's an example: https://github.com/dimitri/pgextwlist/commit/c26e14956028b156271398230fcd8dc0237a188c. Do you want to have a try at it?

**Comment by bradnicholson** [comment]
While I'd love to, I lack the familiarity with both C and the Postgres internals to take it on.

**Comment by ChristophBerg** [comment]
I just gave this a try. The necessary changes for PG10 are unfortunately not trivial, the datastructures passed around in the executor have been extensively changed (List -> RawStmt, more things are PreparedStmt now), so just throwing in a few #ifdef isn't enough.
My current attempt is 8d48b4011adb261020b5a61389ffef55eaaa2c69, but I don't think I'm going to continue working on it, it be better if someone with more knowledge about the executor internals took it up.

**Comment by ChristophBerg** [comment]
Fwiw, I've asked for the removal of pgextwlist from Debian because it is blocking the PG 9.6->10 transition. If people are interested in keeping it in there, we'd need a fix.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=878440

**Comment by ChristophBerg** [comment]
Wow, that was fast! Will stop the removal in Debian, and update the package now.
Thanks!

**Comment by saaros** [comment]
No problem, was going to submit the pull request earlier but forgot to do it before I saw your previous comment.

It'd be nice to set up Travis tests for pgextwlist to make sure it works with all supported versions; pgmemcache has something like that: https://github.com/ohmu/pgmemcache/blob/master/.travis.yml

**Comment by dimitri** [comment]
Thanks guys! Do you need me to setup the Travis integration for the project? In your example from pgmemcache it looks really easy to do, but it's missing the pg9.6 and pg10 targets, for which I think we need to add apt.pg.o to the debian instance in Travis, right?

**Comment by ChristophBerg** [comment]
I have a travis file that works with apt.postgresql.org: https://github.com/ChristophBerg/postgresql-unit/blob/master/.travis.yml

**Comment by ChristophBerg** [comment]
@dimitri: I think you need to enable travis for the repo on the travis site first.

**Comment by dimitri** [comment]
Just added Travis-CI integration. @Myon, can you push your `.travis.yml` file, it seems it is generic and should just work, right?
