### ISSUE TITLE
EREPORT_EXTENSION_IS_NOT_WHITELISTED without usage.

### ISSUE THREAD

**Issue by SamYuan1990** [dimitri/pgextwlist#38]
Hi

I had installed wlist extension and tested with `create extension foo;`

What I am expected to see is an error message like:
```
ERROR:  extension "foo" is not whitelisted
```

But I got:

```
postgres=# create extension foo;
ERROR:  could not open extension control file "/usr/share/postgresql/10/extension/foo.control": No such file or directory
```

Further checked with code v1.10, 1.02
It seems in `pgextwlist/pgextwlist.c`
`EREPORT_EXTENSION_IS_NOT_WHITELISTED` is defined without usage.

Please advise.

Thanks
Sam

**Comment by df7cb** [comment]
Try as non-superuser.

**Comment by SamYuan1990** [comment]
@df7cb , yep non-superuser....

or could you give me more detail about what's kind of super user own should I verify via sql?

**Comment by df7cb** [comment]
TBH, I still don't fully understand the question.

If you want to verify if foo is whitelisted, `set role someoneelse;` first.
