### ISSUE TITLE
Custom script `@current_user@` returning current superuser

### ISSUE THREAD

**Issue by benjaminjb** [dimitri/pgextwlist#39]
I've tried to use the `@current_user@` tag in my custom scripts in order to grant permissions to the schema being created by the extension, but when I do, I see that the schema only has rights granted to the superuser `postgres` being used to run the extension creation. Am I missing something or mis-configuring something?

**Comment by df7cb** [comment]
I don't think that's easily fixable in extwlist, the extension script is really running as the "bootstrap" super user.
