### ISSUE TITLE
Add before and after drop hooks

### ISSUE THREAD

**Issue by ncode** [dimitri/pgextwlist#48]
Hello,

Thank you very much for the work on pgextwlist. It really simplifies a lot granting the ability for users to manage their own extensions. 

I noticed that currently only create and update extensions have support for hooks. Would it be possible to also add hooks for drop extensions or would you accept a PR for it? The use case is for extensions like postgis topology where the extensions creates a schema on the user database. If you grant usage of the schema and not ownership, after removing the extension the user is unable to drop the schema.

**Comment by dimitri** [comment]
Hi @ncode, I'm not sure I understand which hooks you're referring to, could you offer more details? See the following for instance, where we have a hook for DROP EXTENSION:

https://github.com/dimitri/pgextwlist/blob/95919076baa36d368ee0a630128afcf476265ee8/pgextwlist.c#L350

**Comment by valeriecodes** [comment]
Thanks @dimitri, I found this issue because I'm looking for a way to use the custom scripts on extension drop, e.g. ``${extwlist.custom_path}/extname/after-drop.sql``. Is this possible?

**Comment by df7cb** [comment]
We have code to run hook scripts, but the code path for dropping extensions doesn't run it. I'll have a look.
