### ISSUE TITLE
Works unreliably on PG15

### ISSUE THREAD

**Issue by df7cb** [dimitri/pgextwlist#49]
While the CI on github thinks everything is ok: https://github.com/dimitri/pgextwlist/actions/runs/2846023552
... the CI on apt.pg.o does not: https://pgdgbuild.dus.dg-i.net/job/pgextwlist-autopkgtest-beta/architecture=amd64,distribution=sid/19/console#console-section-6

I can also reproduce the issue on my local system.

What's weird is that in the 2nd link above, only the *2nd* CREATE EXTENSION is failing:

```
22:19:10  CREATE EXTENSION citext;
22:19:10  CREATE EXTENSION pg_trgm;
22:19:10 +ERROR:  permission denied to create extension "pg_trgm"
22:19:10 +HINT:  Must have CREATE privilege on current database to create this extension.
```

... while in my local test, both fail:

```
 CREATE EXTENSION citext;
+ERROR:  permission denied to create extension "citext"
+HINT:  Must have CREATE privilege on current database to create this extension.
 CREATE EXTENSION pg_trgm;
+ERROR:  permission denied to create extension "pg_trgm"
+HINT:  Must have CREATE privilege on current database to create this extension.
```

Things were still OK on apt.pg.o one month ago, so this is probably triggered by some change in the toolchain (gcc-12 etc.)

**Comment by df7cb** [comment]
Fwiw it just failed here on bullseye with 15beta3 as well, so it's likely more a change in PG than in the OS that triggered it. (Given the unstable nature, it was probably already broken before, but didn't trigger.)

**Comment by jiangshuai1995** [comment]
@df7cb great commit !  May I ask which PG15‘s commit affected it?

**Comment by df7cb** [comment]
That was during beta, so you'd have to bisect it.
