### ISSUE TITLE
Security Contact

### ISSUE THREAD

**Issue by mgates** [dimitri/pgextwlist#52]
Hey there - I couldn't find a security contact for the project. Could you let me know where to send a security issue (and perhaps add it to the readme?)

Thanks,
Micah

**Comment by df7cb** [comment]
That would be Dimitri and me:
Dimitri Fontaine <dim@tapoueh.org>, Christoph Berg <myon@debian.org>

**Comment by mgates** [comment]
Great, thanks - I had emailed Dimitri on a a guess a few days ago, but I'll resend to both for coordination. Thanks!
