### ISSUE TITLE
error: 'pstmt' undeclared (first use in this function)

### ISSUE THREAD

**Issue by zlcnju** [dimitri/pgextwlist#53]
when PG_MAJOR_VERSION < 1300, the make will fail because the undeclared pstmt. This [commit](https://github.com/dimitri/pgextwlist/commit/2574424804c93c0ee95d3d56e06417783f94e31b) is releated

**Comment by df7cb** [comment]
Works here.

On what platform is this, how are you invoking the build, and what's the full output?

**Comment by df7cb** [comment]
No reply, closing.
